# 실행 전 http-client.private.env.json 파일 확인과 환경변수 설정이 필요

# 게시글 조회
GET {{server}}/blog

### 게시글 작성
POST {{server}}/blog
Content-Type: application/json

{
  "title": "테스트용!",
  "content": "테스트용!",
  "author": "만든이"
}

### 특정 게시글 조회
GET {{server}}/blog/66543f37460b7bdd23e73eeb

### 게시글 삭제
DELETE {{server}}/blog/6656d00b7300d11074842bda

### 게시글 수정
PUT {{server}}/blog/66591e8766574edf4c643c24
Content-Type: application/json

{
  "title": "수정된 타이틀!",
  "content": "수정된 내용!!",
  "author": "수정한사람!"
}